### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by Dattel** [sh00t2kill/HA-Bring-ToDo-List#9]
Hi,
i'm struggeling getting the integration running. There is an error during login. 
on https://web.getbring.com/login i need my emailadress an a "magic loginlink" which is provided by email.
Maybe the reason is, that i'm initially using my google account for login instead of an explicite email/password combination?
Is there any way to make it work?

```
│
│   [31m2023-12-22 16:03:34.795 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session[0m                                          │
│   [31m2023-12-22 16:03:34.795 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector[0m                                               │
│   [31m2023-12-22 16:07:36.364 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Bring Todo Integration for bring               │
│   Traceback (most recent call last):                                                                                                                  │
│     File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup                                                           │
│       result = await component.async_setup_entry(hass, self)                                                                                          │
│                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                          │
│     File "/config/custom_components/bring/__init__.py", line 38, in async_setup_entry                                                                 │
│       await bring.login()                                                                                                                             │
│     File "/config/custom_components/bring/bring.py", line 136, in login                                                                               │
│       login = await self.__get(BRING_URL, "bringlists", params=params)                                                                                │
│               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                │
│     File "/config/custom_components/bring/bring.py", line 112, in __get                                                                               │
│       await self.check_response(response)                                                                                                             │
│     File "/config/custom_components/bring/bring.py", line 93, in check_response                                                                       │
│       raise Exception(message if message else result)                                                                                                 │
│   Exception: {'message': 'email password combination not existing', 'error': 'unauthorized', 'error_description': 'Not authorized to access this re   │
│   source', 'errorcode': 200}[0m                                                                                                                       │
│   [31m2023-12-22 16:07:36.366 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session[0m                                          │
│   [31m2023-12-22 16:07:36.367 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector[0m    
```

**Comment by Dattel** [comment]
currently i'm using a separate account with email/password and a shared list from my google account... that works :-D

**Comment by sh00t2kill** [comment]
Yeah using SSO will not work. I'm unsure if that's possible within HA, I haven't come across another integration using it.
